<a href="https://colab.research.google.com/github/rahulsonarr/Machine-Learning/blob/main/1.%20Libraries%20for%20machine%20learning/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy: NumPy is a fundamental library for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.

In [15]:
import numpy as np

# Creating a 1-dimensional array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1d)
print("Shape:", arr1d.shape)
print("Size:", arr1d.size)
print()

1D Array:
[1 2 3 4 5]
Shape: (5,)
Size: 5



In [16]:
# Creating a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:")
print(arr2d)
print("Shape:", arr2d.shape)
print("Size:", arr2d.size)
print()

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6



In [17]:
# Accessing elements in a NumPy array
print("First element of arr1d:", arr1d[0])
print("Element at row 1, column 2 of arr2d:", arr2d[1, 2])
print()

First element of arr1d: 1
Element at row 1, column 2 of arr2d: 6



In [18]:
# Slicing arrays
print("Slice of arr1d:", arr1d[1:4])
print("Slice of arr2d:")
print(arr2d[:, 1:])  # Selecting all rows and columns starting from column index 1
print()

Slice of arr1d: [2 3 4]
Slice of arr2d:
[[2 3]
 [5 6]]



In [19]:
# Reshaping arrays
reshaped_arr = arr1d.reshape(5, 1)
print("Reshaped array:")
print(reshaped_arr)
print("Shape:", reshaped_arr.shape)
print()

Reshaped array:
[[1]
 [2]
 [3]
 [4]
 [5]]
Shape: (5, 1)



In [20]:
# Array arithmetic operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Dot product:", np.dot(a, b))
print()

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Dot product: 32



In [21]:
# Basic statistical operations
data = np.array([2, 4, 6, 8, 10])
print("Mean:", np.mean(data))
print("Median:", np.median(data))
print("Standard Deviation:", np.std(data))
print("Minimum value:", np.min(data))
print("Maximum value:", np.max(data))

Mean: 6.0
Median: 6.0
Standard Deviation: 2.8284271247461903
Minimum value: 2
Maximum value: 10
